In [1]:
import pandas as pd

**BUSINESS DEPARTMENT**

In [5]:
product_list = pd.read_excel("/content/drive/MyDrive/Project Dataset/Business Department/product_list.xlsx")

product_list

,Unnamed: 0,product_id,product_name,product_type,price
0,0,PRODUCT16794,Grandmas swedish thin pancakes,readymade_breakfast,12.81
1,1,PRODUCT61957,Chili jack oven omelet,readymade_breakfast,9.95
2,2,PRODUCT23890,Baked pears,readymade_breakfast,10.04
3,3,PRODUCT52912,Best buttermilk pancakes,readymade_breakfast,5.83
4,4,PRODUCT56387,Blackberry breakfast bars,readymade_breakfast,14.00
...,...,...,...,...,...
745,445,PRODUCT35203,tomato,grocery,17.28
746,446,PRODUCT34682,bowl,kitchenware,17.28
747,447,PRODUCT07137,dehumidifier,electronics and technology,38.07
748,448,PRODUCT29484,rice,grocery,17.28
749,449,PRODUCT22046,dove deodorant,health and hygiene,6.11

**CUSTOMER MANAGEMENT**

In [9]:
user_credit_card = pd.read_pickle("/content/drive/MyDrive/Project Dataset/Customer Management Department/user_credit_card.pickle")

user_credit_card

user_job = pd.read_csv("/content/drive/MyDrive/Project Dataset/Customer Management Department/user_job.csv")
user_job

,user_id,creation_date,name,street,state,city,country,birthdate,gender,device_address,user_type
0,USER40678,2021-03-17 22:56:13,Zion Feest,14938 West Trace side,New Jersey,Birmingham,Hong Kong,1998-04-06 05:29:37,male,17:fb:f2:60:94:4b,basic
1,USER08728,2022-10-10 12:53:20,Kattie Bergstrom,4476 West Haven fort,Alabama,Irvine,Mayotte,2003-05-22 11:16:19,male,b0:17:a7:0b:d6:67,premium
2,USER29759,2020-05-20 04:34:44,Aiden Corwin,59980 North Crest chester,North Carolina,Tampa,Iraq,2008-08-29 16:42:05,female,24:f2:0b:88:2f:bd,basic
3,USER16806,2021-05-28 07:36:30,Vince Gislason,541 Radial mouth,Illinois,Orlando,New Zealand,2012-02-09 14:12:37,male,a4:f5:fd:fe:07:f9,basic
4,USER27644,2023-03-16 19:25:35,Adele Okuneva,896 Glen bury,Arizona,Reno,Mexico,1976-10-13 00:53:54,male,ac:80:b3:bc:8d:5f,premium
...,...,...,...,...,...,...,...,...,...,...,...
4995,USER49969,2021-11-18 19:04:30,Kendall Waelchi,792 North Manors haven,Florida,San Diego,Jersey,1996-03-11 09:05:32,female,8e:57:7e:62:90:b4,basic
4996,USER57209,2022-03-27 09:17:43,Lucious Kshlerin,48282 Burgs chester,Kentucky,Garland,Ethiopia,2013-07-07 08:53:27,female,00:35:b5:e4:e1:aa,basic
4997,USER36424,2022-10-05 21:36:56,Cordie Jenkins,8928 North Mountains haven,North Dakota,Scottsdale,Tonga,1991-05-18 05:07:36,male,0b:0d:57:d6:c1:ab,basic
4998,USER45166,2020-07-20 03:51:41,Tyrel Feil,920 New Manor port,Rhode Island,Arlington,Virgin Islands (U.S.),1975-12-19 02:27:16,male,83:c9:1e:4e:52:f4,premium
4999,USER54154,2020-05-13 08:43:26,Betty Zieme,19808 North Pass side,Colorado,Detroit,Zambia,2010-02-21 02:56:06,female,4c:fb:dc:fb:b7:e7,premium

In [ ]:
user_data = pd.read_json("/content/drive/MyDrive/Project Dataset/Customer Management Department/user_data.json")

user_data

In [10]:
user_job = pd.read_csv("/content/drive/MyDrive/Project Dataset/Customer Management Department/user_job.csv")
user_job

      Unnamed: 0    user_id              name       job_title   job_level
0              0  USER40678        Zion Feest      Technician    Accounts
1              1  USER08728  Kattie Bergstrom      Technician   Solutions
2              2  USER29759      Aiden Corwin         Student         NaN
3              3  USER16806    Vince Gislason         Student         NaN
4              4  USER27644     Adele Okuneva       Associate   Usability
...          ...        ...               ...             ...         ...
4995        4995  USER49969   Kendall Waelchi     Facilitator  Directives
4996        4996  USER57209  Lucious Kshlerin         Student         NaN
4997        4997  USER36424    Cordie Jenkins  Representative  Directives
4998        4998  USER45166        Tyrel Feil      Supervisor     Metrics
4999        4999  USER54154       Betty Zieme         Student         NaN

[5000 rows x 5 columns]

**ENTERPRISE DEPARTMENT**

In [12]:
merchant_data = pd.read_html("/content/drive/MyDrive/Project Dataset/Enterprise Department/merchant_data.html")
merchant_data

[      Unnamed: 0    merchant_id        creation_date                 name  \
 0              0  MERCHANT53971  2022-06-28 11:42:04         Whitby Group
 1              1  MERCHANT56138  2020-08-27 20:35:19           YourMapper
 2              2  MERCHANT31852  2021-08-05 12:04:33     United Mayflower
 3              3  MERCHANT63299  2021-08-15 19:00:03         TransparaGov
 4              4  MERCHANT16722  2023-02-28 20:35:34             Maponics
 ...          ...            ...                  ...                  ...
 4995        4995  MERCHANT54074  2021-10-16 18:18:52         KLD Research
 4996        4996  MERCHANT41034  2020-04-25 23:45:42              LoopNet
 4997        4997  MERCHANT55677  2020-07-25 13:12:36  Marlin & Associates
 4998        4998  MERCHANT44767  2021-09-28 21:25:24            Accenture
 4999        4999  MERCHANT58991  2020-12-03 12:58:45      Arpin Van Lines

                      street           state           city  \
 0       813 North Isle bury  South Carolina          Boise
 1        54861 Springs view        Colorado      Cleveland
 2     730 East Islands side        Virginia        Atlanta
 3          2619 Coves haven           Maine   Indianapolis
 4     979 North Rue borough         Wyoming          Boise
 ...                     ...             ...            ...
 4995      5760 Rapids mouth     Connecticut        Wichita
 4996         532 Walks bury            Iowa        Madison
 4997        44600 Park port    South Dakota        Wichita
 4998  217 West Estates stad        Michigan  San Francisco
 4999       12166 Coves berg   West Virginia     Scottsdale

                         country  contact_number
 0             Brunei Darussalam    661.157.5528
 1     Sint Maarten (Dutch part)   (046)415-8092
 2                          Mali    939.273.0312
 3                          Chad  1-181-438-5899
 4                     Guatemala    494-319-8223
 ...                         ...             ...
 4995                   Holy See   (499)792-6191
 4996                       Oman    484.217.8833
 4997                 Mauritania  1-681-783-5079
 4998                      Egypt    628-405-2478
 4999               South Africa  1-678-937-3157

 [5000 rows x 9 columns]]

In [13]:
order_with_merchant_data1 = pd.read_parquet("/content/drive/MyDrive/Project Dataset/Enterprise Department/order_with_merchant_data1.parquet")
order_with_merchant_data1

                                   order_id    merchant_id      staff_id
0      eac330c0-457a-4faa-b15a-52a3c440e7f3  MERCHANT58557  STAFF0027757
1      e1beaf61-e687-4e70-bdd4-3ea338139a0b   MERCHANT0605  STAFF0039068
2      0612c246-57f1-40e8-9993-0f8d41992049  MERCHANT22282  STAFF0058495
3      a800f0d9-47d8-455b-b096-622e76156705  MERCHANT39307  STAFF0038632
4      b4c411de-2fd3-4806-91ae-165edc9baa12  MERCHANT26962  STAFF0035568
...                                     ...            ...           ...
99995  a72f9936-fea8-427c-869b-a9587e0dfebe  MERCHANT11270  STAFF0016364
99996  d55e57f3-0543-4725-8b2c-007958b7b858  MERCHANT54423  STAFF0043207
99997  758e9edc-b790-47c5-b785-426919339ef1  MERCHANT55289  STAFF0054414
99998  f662ffdf-32ae-4a5f-a326-de658db9eb5d  MERCHANT39525  STAFF0064079
99999  8ed751f5-80ae-454d-bac6-2e98c138cb65   MERCHANT7346  STAFF0013034

[100000 rows x 3 columns]

In [14]:
order_with_merchant_data2 = pd.read_parquet("/content/drive/MyDrive/Project Dataset/Enterprise Department/order_with_merchant_data2.parquet")
order_with_merchant_data2

                                    order_id    merchant_id      staff_id
100000  848f9cad-c4d3-4822-83e9-322ae73261c3   MERCHANT9789  STAFF0020354
100001  be97922b-20fb-4244-9e25-bac98b209668  MERCHANT43424  STAFF0061355
100002  dc905240-5fcd-45e4-8077-be831e1f0263  MERCHANT23900  STAFF0038795
100003  11cd8029-61f2-4bc8-a148-cb1a4afd8b57  MERCHANT58797  STAFF0023844
100004  69c9e6fc-326e-4f2d-98c6-5360b91cfb84  MERCHANT41587  STAFF0022537
...                                      ...            ...           ...
299995  86f5d57b-a787-43ed-8b2c-f4f9a52f5033  MERCHANT15934  STAFF0009370
299996  7a57393e-7c8f-4d9c-ba3c-4711e739fd6e   MERCHANT0688  STAFF0022143
299997  5c442281-170a-4344-8d0f-3c31f3f02b25  MERCHANT58009  STAFF0018140
299998  aecebd35-355e-4f87-acc7-bcca013dceed  MERCHANT33284  STAFF0023079
299999  a2498394-9e81-4416-b0ea-443e584e77cc   MERCHANT1615  STAFF0008378

[200000 rows x 3 columns]

In [16]:
order_with_merchant_data3 = pd.read_csv("/content/drive/MyDrive/Project Dataset/Enterprise Department/order_with_merchant_data3.csv")

order_with_merchant_data3

,Unnamed: 0,order_id,merchant_id,staff_id
0,300000,e8bafe72-d506-4437-b357-f38682353238,MERCHANT13004,STAFF0009879
1,300001,eae5e846-c16b-4959-9f90-331c355951ff,MERCHANT17176,STAFF0045676
2,300002,913f901b-d488-49be-bcaf-86fcd581a528,MERCHANT0855,STAFF0031852
3,300003,8479d795-6c4d-41d0-a0c7-4ca9c3c3ca31,MERCHANT40576,STAFF0052472
4,300004,2aaae5b3-c858-4d05-b92f-cd2085201c66,MERCHANT32289,STAFF0031305
...,...,...,...,...
199995,499995,ba506489-1505-481d-b0b1-8cdbf04a515f,MERCHANT64706,STAFF0002455
199996,499996,551a54f1-1a7f-4a1d-a7c7-62afb433b4f4,MERCHANT12240,STAFF0065523
199997,499997,2b2e775f-d6cd-4659-9a88-b4950bc326c0,MERCHANT39339,STAFF0039868
199998,499998,949eb760-8022-4f0b-9e6c-3ddb049a25fd,MERCHANT1546,STAFF0041085
199999,499999,4d1c5613-a48e-4b18-b016-bb639a1d5490,MERCHANT10900,STAFF0057025

In [18]:
staff_data = pd.read_html("/content/drive/MyDrive/Project Dataset/Enterprise Department/staff_data.html")

staff_data

[      Unnamed: 0      staff_id               name     job_level  \
 0              0  STAFF0009650  Randall Bergstrom  intermediate
 1              1  STAFF0039964   Christian Hessel  intermediate
 2              2  STAFF0044932      Edgardo Fadel         entry
 3              3  STAFF0015819    Jordi Gleichner         entry
 4              4  STAFF0036616        Price Hintz  intermediate
 ...          ...           ...                ...           ...
 4995        4995  STAFF0023027    Felicia Keeling  intermediate
 4996        4996  STAFF0046023      Leonardo Wiza  intermediate
 4997        4997  STAFF0021174        Blake Huels         entry
 4998        4998  STAFF0000759       Darrell Ward  intermediate
 4999        4999  STAFF0008057      Idell Kilback         entry

                        street         state                city  \
 0            376 Land chester         Texas               Omaha
 1         945 West Camp shire    New Mexico           San Diego
 2         997 Expressway town  Rhode Island      Corpus Christi
 3           720 Centers burgh      Virginia         Bakersfield
 4     1720 North Skyway burgh       Alabama          Scottsdale
 ...                       ...           ...                 ...
 4995         8564 Courts town         Idaho             Anaheim
 4996     997 Port Branch bury     Minnesota             Raleigh
 4997        4498 Bypass shire       Indiana  Nashville-Davidson
 4998      1934 New Flats fort   Mississippi             Chicago
 4999     256 East Courts view     Tennessee           Charlotte

                   country  contact_number        creation_date
 0            Cook Islands   (138)548-8481  2020-09-04 02:33:28
 1                Pakistan    393-164-5574  2020-08-08 06:50:47
 2                 Albania    328.133.8850  2020-02-10 16:49:18
 3             Timor-Leste    649.258.8115  2021-06-11 11:30:29
 4     Palestine, State of    977-698-2305  2020-08-10 10:37:55
 ...                   ...             ...                  ...
 4995          Timor-Leste    167-344-4583  2023-03-17 14:32:11
 4996               Israel  1-589-339-3757  2020-02-26 06:34:01
 4997               Zambia    523.422.0032  2023-03-17 21:09:18
 4998            Greenland    661-368-4699  2022-01-13 09:45:18
 4999              Bahrain    995-556-9058  2021-06-01 10:05:25

 [5000 rows x 10 columns]]

**MARKETING DEPARTMENT**

In [20]:
campaign_data = pd.read_csv("/content/drive/MyDrive/Project Dataset/Marketing Department/campaign_data.csv", sep="\t")

campaign_data

,Unnamed: 0,campaign_id,campaign_name,campaign_description,discount
0,0,CAMPAIGN24776,wouldn't you know it,"""Twee retro vinyl single-origin coffee sartori...",1%
1,1,CAMPAIGN33679,could be written on the back of a postage stamp,"""Fanny pack gentrify cardigan messenger bag."" ...",1pct
2,2,CAMPAIGN49972,me neither,"""DIY pug leggings everyday craft beer cardigan...",10%%
3,3,CAMPAIGN61872,on the huh,"""Trust fund pinterest chambray."" - Claude Aufd...",5%
4,4,CAMPAIGN03110,stick a fork in it,"""YOLO tumblr Yuccie austin."" - Jordi Kunde",1percent
5,5,CAMPAIGN46302,you must be new here,"""Craft beer XOXO hella tacos chillwave cred or...",1pct
6,6,CAMPAIGN11190,mind your own beeswax,"""Street shoreditch viral before they sold out ...",10pct
7,7,CAMPAIGN53595,how do I get to the train station,"""Craft beer venmo lomo fixie readymade marfa.""...",20pct
8,8,CAMPAIGN29983,would it hurt,"""Vegan migas ramps keytar wolf cray kickstarte...",1%
9,9,CAMPAIGN52447,pound for pound,"""Semiotics biodiesel everyday craft beer etsy ...",1percent

In [22]:
transactional_campaign_data = pd.read_csv("/content/drive/MyDrive/Project Dataset/Marketing Department/transactional_campaign_data.csv")

transactional_campaign_data

,Unnamed: 0,transaction_date,campaign_id,order_id,estimated arrival,availed
0,2,2023-08-14,CAMPAIGN49972,0612c246-57f1-40e8-9993-0f8d41992049,10days,1
1,4,2021-10-12,CAMPAIGN46302,b4c411de-2fd3-4806-91ae-165edc9baa12,13days,0
2,6,2023-01-30,CAMPAIGN29983,26de6b40-db2d-40b9-a64c-58736eaf0381,3days,1
3,8,2022-01-05,CAMPAIGN46302,26b60a4e-aafe-4b99-bace-034d088a4a53,8days,1
4,9,2023-09-19,CAMPAIGN46302,4aab29ae-e610-46bf-92af-199f6f420cee,14days,1
...,...,...,...,...,...,...
124882,499990,2022-04-14,CAMPAIGN61872,6a5163c2-ba62-461c-a729-5b06fe266bd9,12days,0
124883,499991,2022-11-23,CAMPAIGN11190,883e2fe2-bbdf-4b5e-8348-c2bcba07da0e,15days,1
124884,499992,2023-07-28,CAMPAIGN33679,575b0a2d-5539-4565-a10b-1f4f6516cd27,12days,1
124885,499995,2020-04-12,CAMPAIGN49972,ba506489-1505-481d-b0b1-8cdbf04a515f,6days,1
124886,499997,2023-03-24,CAMPAIGN52447,2b2e775f-d6cd-4659-9a88-b4950bc326c0,15days,1

In [23]:
line_item_data_prices1 = pd.read_csv("/content/drive/MyDrive/Project Dataset/Operations Department/line_item_data_prices1.csv")

line_item_data_prices1

        Unnamed: 0                              order_id  price quantity
0                0  8d8acbac-ccbb-4609-a978-98dee3ac3088  12.81      6px
1                1  59e4c308-5262-486d-9f1a-12b1278e3c44  14.00  6pieces
2                2  30fc1b76-c488-4077-8d70-3236e3afc990   6.78     4pcs
3                3  6b273d38-b472-4bb2-8b74-a26705c707fa   8.72      4px
4                4  6b273d38-b472-4bb2-8b74-a26705c707fa   8.83  5pieces
...            ...                                   ...    ...      ...
499995      499995  61c1751e-f17b-494a-a9a2-33c6694d6036  38.07   1piece
499996      499996  61c1751e-f17b-494a-a9a2-33c6694d6036  38.07     3pcs
499997      499997  44f739c2-73f4-491c-a932-c1362831e0e3  38.07  1pieces
499998      499998  44f739c2-73f4-491c-a932-c1362831e0e3  38.07      1PC
499999      499999  f1c591a5-fd7c-498f-ae4e-2739334878ce  38.07  1pieces

[500000 rows x 4 columns]

In [24]:
line_item_data_prices2 = pd.read_csv("/content/drive/MyDrive/Project Dataset/Operations Department/line_item_data_prices2.csv")

line_item_data_prices2

        Unnamed: 0                              order_id  price quantity
0           500000  f1c591a5-fd7c-498f-ae4e-2739334878ce  38.07      4PC
1           500001  8a720341-a145-4a7c-b2d5-ac3c6e0d8da8  38.07     4pcs
2           500002  8a720341-a145-4a7c-b2d5-ac3c6e0d8da8  38.07     4PCs
3           500003  fd365f1c-9c25-4544-b4b2-fd9f55d3e6e2  38.07     2PCs
4           500004  fd365f1c-9c25-4544-b4b2-fd9f55d3e6e2  38.07  4pieces
...            ...                                   ...    ...      ...
499995      999995  1e199808-c7b5-4fba-ab74-6ff46d3195fb  38.62   5piece
499996      999996  552e5cdc-6e1d-4b90-a721-012644ffc42f  36.11     9PCs
499997      999997  552e5cdc-6e1d-4b90-a721-012644ffc42f  36.11     5pcs
499998      999998  060d9363-3ce4-4acf-9195-5c9e6d835fc5  52.55      5PC
499999      999999  060d9363-3ce4-4acf-9195-5c9e6d835fc5  52.55    10pcs

[500000 rows x 4 columns]

In [25]:
line_item_data_prices3 = pd.read_parquet("/content/drive/MyDrive/Project Dataset/Operations Department/line_item_data_prices3.parquet")

line_item_data_prices3

        Unnamed: 0                              order_id  price quantity
0          1000000  dc70f978-3a6b-4baf-b97e-4a88690a34fe  42.13      8PC
1          1000001  dc70f978-3a6b-4baf-b97e-4a88690a34fe  42.13   5piece
2          1000002  3556b3e7-046a-4148-b1cb-d86ee7ee5421  42.13     10PC
3          1000003  3556b3e7-046a-4148-b1cb-d86ee7ee5421  42.13     5pcs
4          1000004  29b63149-3b3c-4309-a751-7d0a563f7c12  40.87      5PC
...            ...                                   ...    ...      ...
997169     1997169  8a985165-e1b4-4f91-a8c4-86f54c806a9c  17.28     5pcs
997170     1997170  7285b9ed-a45a-4aa0-86fb-2abae50780f8  17.28   5piece
997171     1997171  35ad8f1d-9014-4430-bed3-f803b46d48a6  38.07     6PCs
997172     1997172  38320c44-fea2-46b1-adfc-c4be22865c78  17.28  3pieces
997173     1997173  0446efea-bbb6-4d85-aa6e-51381f440595  17.28   4piece

[997174 rows x 4 columns]

In [26]:
line_item_data_products1 = pd.read_csv("/content/drive/MyDrive/Project Dataset/Operations Department/line_item_data_products1.csv")

line_item_data_products1

,Unnamed: 0,order_id,product_name,product_id
0,0,8d8acbac-ccbb-4609-a978-98dee3ac3088,Grandmas swedish thin pancakes,PRODUCT16794
1,1,59e4c308-5262-486d-9f1a-12b1278e3c44,Blackberry breakfast bars,PRODUCT56387
2,2,30fc1b76-c488-4077-8d70-3236e3afc990,Moms cheat doughnuts,PRODUCT26612
3,3,6b273d38-b472-4bb2-8b74-a26705c707fa,Baked swiss cheese omelet,PRODUCT17344
4,4,6b273d38-b472-4bb2-8b74-a26705c707fa,Egg flowers,PRODUCT07816
...,...,...,...,...
499995,499995,61c1751e-f17b-494a-a9a2-33c6694d6036,clock,PRODUCT14601
499996,499996,61c1751e-f17b-494a-a9a2-33c6694d6036,clock,PRODUCT14601
499997,499997,44f739c2-73f4-491c-a932-c1362831e0e3,clock,PRODUCT14601
499998,499998,44f739c2-73f4-491c-a932-c1362831e0e3,clock,PRODUCT14601
499999,499999,f1c591a5-fd7c-498f-ae4e-2739334878ce,clock,PRODUCT14601

In [27]:
line_item_data_products2 = pd.read_csv("/content/drive/MyDrive/Project Dataset/Operations Department/line_item_data_products2.csv")

line_item_data_products2

,Unnamed: 0,order_id,product_name,product_id
0,500000,f1c591a5-fd7c-498f-ae4e-2739334878ce,clock,PRODUCT14601
1,500001,8a720341-a145-4a7c-b2d5-ac3c6e0d8da8,book of jokes,PRODUCT63300
2,500002,8a720341-a145-4a7c-b2d5-ac3c6e0d8da8,book of jokes,PRODUCT63300
3,500003,fd365f1c-9c25-4544-b4b2-fd9f55d3e6e2,book of jokes,PRODUCT63300
4,500004,fd365f1c-9c25-4544-b4b2-fd9f55d3e6e2,book of jokes,PRODUCT63300
...,...,...,...,...
499995,999995,1e199808-c7b5-4fba-ab74-6ff46d3195fb,Goat cheese black olive mashed potatoes,PRODUCT23102
499996,999996,552e5cdc-6e1d-4b90-a721-012644ffc42f,Maple coffee,PRODUCT26180
499997,999997,552e5cdc-6e1d-4b90-a721-012644ffc42f,Maple coffee,PRODUCT26180
499998,999998,060d9363-3ce4-4acf-9195-5c9e6d835fc5,Sweet onion and mashed potato bake,PRODUCT22318
499999,999999,060d9363-3ce4-4acf-9195-5c9e6d835fc5,Sweet onion and mashed potato bake,PRODUCT22318

In [28]:
line_item_data_products3 = pd.read_parquet("/content/drive/MyDrive/Project Dataset/Operations Department/line_item_data_products3.parquet")

line_item_data_products3

,Unnamed: 0,order_id,product_name,product_id
0,1000000,dc70f978-3a6b-4baf-b97e-4a88690a34fe,Swedish cucumber salad pressgurka,PRODUCT20506
1,1000001,dc70f978-3a6b-4baf-b97e-4a88690a34fe,Swedish cucumber salad pressgurka,PRODUCT20506
2,1000002,3556b3e7-046a-4148-b1cb-d86ee7ee5421,Swedish cucumber salad pressgurka,PRODUCT20506
3,1000003,3556b3e7-046a-4148-b1cb-d86ee7ee5421,Swedish cucumber salad pressgurka,PRODUCT20506
4,1000004,29b63149-3b3c-4309-a751-7d0a563f7c12,Savory pita chips,PRODUCT34708
...,...,...,...,...
997169,1997169,8a985165-e1b4-4f91-a8c4-86f54c806a9c,tomato,PRODUCT35203
997170,1997170,7285b9ed-a45a-4aa0-86fb-2abae50780f8,tomato,PRODUCT35203
997171,1997171,35ad8f1d-9014-4430-bed3-f803b46d48a6,dehumidifier,PRODUCT07137
997172,1997172,38320c44-fea2-46b1-adfc-c4be22865c78,rice,PRODUCT29484
997173,1997173,0446efea-bbb6-4d85-aa6e-51381f440595,rice,PRODUCT29484

In [30]:
order_data_20200101_20200701 = pd.read_parquet("/content/drive/MyDrive/Project Dataset/Operations Department/order_data_20200101-20200701.parquet")

order_data_20200101_20200701

,order_id,user_id,estimated arrival,transaction_date
12,0248bb48-d0d0-4a11-a158-f620640a757a,USER16283,13days,2020-06-04
19,14473b59-6c4f-429e-89ef-ce920b209df3,USER08179,8days,2020-04-07
25,62b8fabf-4e0a-4383-8b3a-7276c77f9e8c,USER55688,10days,2020-05-07
29,96a01cee-071d-4e10-a9e4-56a31b82a9d5,USER34967,8days,2020-06-05
37,479b1a6c-3a76-41a7-b15d-71acd4045080,USER07130,15days,2020-05-24
...,...,...,...,...
499969,8e35842b-c688-47da-b61f-cfd436f2edde,USER23432,15days,2020-02-10
499980,05ca3879-4ca4-4f53-a94c-13c3de8c92a7,USER36687,8days,2020-02-24
499983,ca6d1f78-97c9-4ece-9c36-eb6b98d8c02d,USER24773,6days,2020-05-16
499984,c2232dd6-cc44-4ec7-a079-1ad1724cb487,USER43039,4days,2020-06-04
499995,ba506489-1505-481d-b0b1-8cdbf04a515f,USER02322,6days,2020-04-12

In [32]:
order_data_20200701_20211001 = pd.read_pickle("/content/drive/MyDrive/Project Dataset/Operations Department/order_data_20200701-20211001.pickle")

order_data_20200701_20211001

,order_id,user_id,estimated arrival,transaction_date
1,e1beaf61-e687-4e70-bdd4-3ea338139a0b,USER36309,13days,2021-01-01
10,4cad07a9-dca9-47a0-86f1-f83671d05260,USER46704,5days,2021-09-22
14,8750f8c5-380c-4bbd-bb54-8a2b5e5958ac,USER32071,10days,2020-07-06
15,3d77b756-0f11-4145-9fac-8f229611ac39,USER47160,3days,2021-09-25
16,3312851e-28dc-4508-8003-09ba304ce9e2,USER15307,11days,2020-07-01
...,...,...,...,...
499964,b638ebb0-396b-48c3-b0e5-286c5976be33,USER34485,4days,2020-11-30
499970,61aa91d0-c989-452b-a688-bb326bb1c440,USER43788,12days,2020-10-11
499979,188833ff-44ee-442d-b405-5ac0be71233e,USER26701,9days,2021-08-31
499985,3e259fd4-8079-4181-b2b9-d8b3db7ca8bd,USER11796,6days,2021-08-09
499996,551a54f1-1a7f-4a1d-a7c7-62afb433b4f4,USER13970,15days,2021-02-26

In [33]:
order_data_20211001_20220101 = pd.read_csv("/content/drive/MyDrive/Project Dataset/Operations Department/order_data_20211001-20220101.csv")

order_data_20211001_20220101

,Unnamed: 0,order_id,user_id,estimated arrival,transaction_date
0,4,b4c411de-2fd3-4806-91ae-165edc9baa12,USER28531,13days,2021-10-12
1,7,d42d7e7a-71bd-43aa-8bed-49d52b74d4eb,USER56935,13days,2021-10-15
2,41,84295de8-90c2-4e67-a1d9-b1ffab45623f,USER11824,13days,2021-10-11
3,43,74a59808-b7f5-4dc1-b441-a8e0e15b49b6,USER51578,15days,2021-10-22
4,61,b3965e7d-23d7-475b-93f0-13b49a999030,USER51925,9days,2021-10-09
...,...,...,...,...,...
32283,499959,a5021293-525b-4f3d-8d6a-16b70bbef542,USER46830,7days,2021-12-03
32284,499965,d5dbea32-829e-474c-8d88-cadcb993a944,USER23251,8days,2021-11-23
32285,499966,590caead-83dd-4273-820c-5bd2c84a92a6,USER14981,12days,2021-11-24
32286,499976,833311eb-cc8d-4348-b7d7-0aecba5b577e,USER62122,12days,2021-11-26
32287,499993,4d0570e9-d6cc-4ef7-95c1-e8c5ec810d37,USER24281,6days,2021-12-06

In [34]:
order_data_20220101_20221201 = pd.read_excel("/content/drive/MyDrive/Project Dataset/Operations Department/order_data_20220101-20221201.xlsx")

order_data_20220101_20221201

,Unnamed: 0,order_id,user_id,estimated arrival,transaction_date
0,0,eac330c0-457a-4faa-b15a-52a3c440e7f3,USER23985,12days,2022-08-13
1,3,a800f0d9-47d8-455b-b096-622e76156705,USER44549,9days,2022-11-11
2,8,26b60a4e-aafe-4b99-bace-034d088a4a53,USER53013,8days,2022-01-05
3,13,96c718b3-0de0-482c-8b05-9081d47314c6,USER55595,8days,2022-05-29
4,21,0e6eeff9-dc85-4e22-9d0d-0758f2e321f6,USER29425,8days,2022-11-17
...,...,...,...,...,...
117168,499982,ceafa665-307f-4c9e-b1bd-79577a450eb9,USER17572,12days,2022-02-14
117169,499986,f628455c-ad0a-444f-96c3-931f6a1912e9,USER21194,9days,2022-01-23
117170,499987,38973532-903e-49e6-9d13-61dd5fdebf6e,USER14772,11days,2022-06-06
117171,499990,6a5163c2-ba62-461c-a729-5b06fe266bd9,USER40321,12days,2022-04-14
117172,499991,883e2fe2-bbdf-4b5e-8348-c2bcba07da0e,USER54177,15days,2022-11-23

In [35]:
order_data_20221201_20230601 = pd.read_json("/content/drive/MyDrive/Project Dataset/Operations Department/order_data_20221201-20230601.json")

order_data_20221201_20230601

,order_id,user_id,estimated arrival,transaction_date
6,26de6b40-db2d-40b9-a64c-58736eaf0381,USER36943,3days,2023-01-30
11,71ef25bd-1146-4ac9-b371-ede0cda08093,USER10211,7days,2023-04-13
34,d06a6ad2-b254-4cc6-8397-4c9bf1a2823e,USER28839,3days,2023-04-05
44,8bfbd31b-5a72-4c80-9e95-9168e9d822e3,USER00089,4days,2023-04-07
45,3fab0712-4542-4779-89cc-29518063ce8f,USER63283,12days,2023-04-18
...,...,...,...,...
499975,1823e6f4-8ce3-4e20-b147-afa70f0e6fc1,USER34522,8days,2023-02-12
499988,222f2012-ca46-4822-ad1a-ed8d80b824b7,USER31933,13days,2022-12-23
499994,1043b5cf-7940-4b3e-93b2-2bdc5d7b7b52,USER59787,14days,2023-03-23
499997,2b2e775f-d6cd-4659-9a88-b4950bc326c0,USER55001,15days,2023-03-24
499999,4d1c5613-a48e-4b18-b016-bb639a1d5490,USER38370,12days,2023-04-03

In [36]:
order_data_20230601_20240101 = pd.read_html("/content/drive/MyDrive/Project Dataset/Operations Department/order_data_20230601-20240101.html")
order_data_20230601_20240101

[       Unnamed: 0                              order_id    user_id  \
 0               2  0612c246-57f1-40e8-9993-0f8d41992049  USER24284
 1               5  74e7c07a-d266-492f-a8f7-22987013d7e1  USER47513
 2               9  4aab29ae-e610-46bf-92af-199f6f420cee  USER50778
 3              18  89c3c238-2ae5-4883-bba5-08e23dbedee3  USER44062
 4              20  03c25b03-a7cc-4758-8490-cdd5dd492646  USER48153
 ...           ...                                   ...        ...
 64041      499974  567ef043-cc78-42af-90cc-9e92a240479f  USER28093
 64042      499981  8fd537e1-a0b6-434f-a928-f37a19c54c05  USER14801
 64043      499989  a2561340-c850-4f85-8e20-e9ceccd10608  USER05932
 64044      499992  575b0a2d-5539-4565-a10b-1f4f6516cd27  USER59342
 64045      499998  949eb760-8022-4f0b-9e6c-3ddb049a25fd  USER04177

       estimated arrival transaction_date
 0                10days       2023-08-14
 1                15days       2023-10-30
 2                14days       2023-09-19
 3                 8days       2023-07-11
 4                15days       2023-07-21
 ...                 ...              ...
 64041             3days       2023-10-08
 64042             3days       2023-10-13
 64043             3days       2023-11-07
 64044            12days       2023-07-28
 64045             4days       2023-08-16

 [64046 rows x 5 columns]]

In [38]:
order_delays = pd.read_html("/content/drive/MyDrive/Project Dataset/Operations Department/order_delays.html")
order_delays

[        Unnamed: 0                              order_id  delay in days
 0            24261  a0c62902-2728-4b38-bf40-89816ebe183f              9
 1           345824  17902aef-e623-48c0-a865-ab427be0f114              7
 2           398475  ce47737b-2253-4ff6-90c6-2b5955d1de1e              7
 3           241232  fc3312cf-f014-4c14-a04d-b26403835c03              5
 4           446720  c0053e4c-5b10-4e31-97f6-2d60866e2fbb              6
 ...            ...                                   ...            ...
 199995      369126  39beb902-0b9f-40ce-a75c-3f9a1186bda1              5
 199996      297765  336c76e4-92fa-463a-b12a-0e67fa177f9c              4
 199997      248134  703941d7-aaff-4f16-b34e-70ec2b3d29bf              0
 199998      274209  f3cdd72c-4a6d-4a34-9388-29b4a46e6b51              2
 199999      330898  5273a961-97c7-48b4-bc81-934ce0833cde              0

 [200000 rows x 3 columns]]